### PR TITLE
Fix event at zero error

### PR DESCRIPTION
**Pull request by brendanbalken**
We have an event at 0 and it breaks the function with no verbose error. Please see proposed change.

Thank you,
Brendan

PS this is my first pull request so please let me know if I did anything wrong. Thanks

### CODE REVIEW

**Comment by arnodelorme** [comment]
Would you mind sharing your data file? We need to check why the problem occurs. Sometimes there are boundaries at latency 0.5 sample which indicate that a portion of data has been removed at the beginning.

**Comment by arnodelorme** [comment]
Hi Brendan, do you have a data file to share for testing purposes?

**Comment by brendanbalken** [comment]
Yes sorry thank you for reminding me. I have 2 data files with this error. It's not something that's supposed to be in the data file. It's a bug in our data collection. So eeglab doesn't need to do anything meaningful with it. Just recognize it as erroneous and throw it out.


Github won't let me upload here so I shared with you via box. Let me know if you have any issues.



Thank you,
Brendan

**Comment by arnodelorme** [comment]
@cll008 see the data https://drive.google.com/file/d/1HKTtakPa7_Y7z6a7yOGAwB6sqXQDq8wD/view?usp=sharing

**Comment by cll008** [comment]
Hi @brendanbalken, thanks for your patience and your contribution. I was unable to reproduce errors with the two files you shared (I used the Neuroscan Curry import plug-in based on the file extension type). 

1. How are you importing the data
2. What sampling rate are you choosing
3. OS?
4. MATLAB version?
5. EEGLAB version?

**Comment by cll008** [comment]
1. Are you using the GUI or the command line?
2. Do you have the Signal Processing toolbox installed or not?
    (do you see "Signal Processing Toolbox absent: using custom interpolation instead of resample() function." in the 
    command window when you resample)

Thanks.

**Pull request closed without merging**
