### PR TITLE
New feature - Custom time interval for channel interpolation

### PR DESCRIPTION
**Pull request by AminAlam**
When interpolating channels of datasets, it is good to have the option of just interpolating a custom time interval of the bad channels instead of the entire time interval. This option is added to the `pop_interp.m` and `eeg_interp.m`. The text field for entering the start and stop of the time interval is shown in the interpolation pop page when the EEG dataset is not epoched.

### CODE REVIEW

**Comment by AminAlam** [comment]
@arnodelorme

**Comment by arnodelorme** [comment]
Thank you for your contribution. This new functionality will select data at the time of interpolation -- however, I do not believe it will interpolate a time window.  Based on the code, it seems that non selected time region will be removed. Is the data length remaining the same?

**Comment by AminAlam** [comment]
> Thank you for your contribution. This new functionality will select data at the time of interpolation -- however, I do not believe it will interpolate a time window.  Based on the code, it seems that non selected time region will be removed. Is the data length remaining the same?

- [ ] Yes, the data length remains the same. Because I didn't want to change the whole structure of interpolation functions, I interpolated the whole dataset and in the end overwrote the parts of dataset which are not indicated for interpolation with the original dataset.

**Comment by arnodelorme** [comment]
Yes, the code makes sense, now. Did you test it on a dataset?

**Comment by AminAlam** [comment]
> Yes, the code makes sense, now. Did you test it on a dataset?

Yes, I tested it. Also, I tested it in two different scenarios: 
1)full dataset interpolation (not indicating interpolation interval) 2)indicating the interpolation interval

It worked fine in both of the scenarios.

**Comment by AminAlam** [comment]
Is there any changes or conflicts that I should apply or resolve?
@arnodelorme

**Comment by arnodelorme** [comment]
Yes, that would be great. A good exercise. Merge the current code to your branch and submit another pull request. WOuld you mind also adding a test call in the comment?

**Comment by AminAlam** [comment]
> Yes, that would be great. A good exercise. Merge the current code to your branch and submit another pull request. WOuld you mind also adding a test call in the comment?

Ok, I will resolve the conflict. Can you please specify what you mean as a test call?

**Comment by arnodelorme** [comment]
A call demonstrating that it works

EEG = pop_loadset(‘eeglab_data.set’);
EEG2 = pop_reref...

**Pull request closed without merging**
