### PR TITLE
Fix typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Ensure backwards compatibility for `homogenous` → `homogeneous`.

See also:
* [What is the difference between homogenous and homogeneous?](https://www.quora.com/What-is-the-difference-between-homogenous-and-homogeneous)
* [Homogenous vs. Homogeneous](https://www.grammar.com/homogenous_vs._homogeneous)
* [Homogenous vs. Homogeneous – What’s the Difference?](https://writingexplained.org/homogenous-vs-homogeneous)
* [homogeneous](https://www.dictionary.com/browse/homogeneous) / [homogenous](https://www.dictionary.com/browse/homogenous) in Dictionary.com

The proper spelling here is _homogeneous_, although _homogenous_ has become quite common in everyday usage:
*  [232 000 000 hits](https://www.google.com/search?q=homogeneous) for _homogeneous_
*  [72 700 000 hits](https://www.google.com/search?q=homogenous) for _homogenous_

### CODE REVIEW

**Comment by arnodelorme** [comment]
The spelling is not unique and this is more than documentation. These are parameters to functions.

**Comment by DimitriPapadopoulos** [comment]
The proper spelling is _homogeneous_. Because these are parameters to functions, I have taken care of backwards compatibility.

**Comment by arnodelorme** [comment]
I have changed this before and it created a lot of issues - so I had to revert the code. 
It is a matter of preference I think for the spelling and I prefer not to break the code.

https://www.biologyonline.com/dictionary/homogenous

I see at least one case where it will create a problem

Line 100 of ttest2_cell
    if strcmpi(homogeneous, 'inhomogeneous')

**Comment by DimitriPapadopoulos** [comment]
Still, the proper spelling _homogeneous_ in dictionaries.

Again, I have taken care of backwards compatibility:
```matlab
    if strcmpi(homogeneous, 'homogenous'), homogeneous = 'homogeneous'; end
    if strcmpi(homogeneous, 'inhomogenous'), homogeneous = 'inhomogeneous'; end
```

**Comment by DimitriPapadopoulos** [comment]
As for this link: https://www.biologyonline.com/dictionary/homogenous

> In biology, it is the old term for [homologous](https://www.biologyonline.com/dictionary/homologous), which is defined as “having corresponding parts, similar structures, or the same anatomical positions”.

**Comment by arnodelorme** [comment]
There were still issues with the code for backward compatibility. Line 101 (last message). If you fix it and also send me tests with all possible old and new calls (homogenous, homegenous, inhomogeneous and inhomogenous) for the 2 modified functions, so I can check the numerical output, I will accept the changes.

**Comment by DimitriPapadopoulos** [comment]
I don't think there is an issue in line 101, because before this line:
```matlab
    if strcmpi(homogeneous, 'homogenous'), homogeneous = 'homogeneous'; end
    if strcmpi(homogeneous, 'inhomogenous'), homogeneous = 'inhomogeneous'; end
```

**Comment by arnodelorme** [comment]
It is always hard to predict issues. I know from experience. Indeed, there should not be an issue. But there could be a typo, etc...

**Comment by DimitriPapadopoulos** [comment]
You're right, tests are a good idea.

**Pull request closed without merging**
