### PR TITLE
ENH - suggested improvements for FT2eeglab conversion if data does no…

### PR DESCRIPTION
**Pull request by schoffelen**
…t contain a header field

### CODE REVIEW

**Comment by schoffelen** [comment]
Hi Arno,
I have some suggestions for fieldtrip2eeglab, to facilitate conversion from an ft-structure to eeglab. The suggestions are based on a situation, where there's no header field in the data. The following code should now work:

% create minimal data structure
data = [];
data.trial{1} = randn(3,100);
data.trial{2} = randn(3,100);
data.time{1}  = (0:99)./100;
data.time{2}  = data.time{1};
data.label    = {'a';'b';'c'};

EEG = fieldtrip2eeglab(data);

% I would expect that this works as well
cfg            = [];
cfg.keeptrials = 'yes';
tlck = ft_timelockanalysis(cfg, data);

EEG2 = fieldtrip2eeglab(tlck);

This relates to https://github.com/fieldtrip/fieldtrip/issues/1857

**Comment by arnodelorme** [comment]
Are you sure the code above is correct. The output of fieldtrip2eeglab is never used. The code crashes but changing fieldtrip2eeglab will not fix anything.

**Comment by schoffelen** [comment]
How do you mean: the output of fieldtrip2eeglab is never used? I guess it may never be used through the GUI, but what if a user wants to move from a fieldtrip data representation to an eeglab data representation, and uses the command line for that?

**Comment by arnodelorme** [comment]
I was confused. I have merged the changes.

**Comment by schoffelen** [comment]
:)

No worries, I am often confused myself...

**Pull request merged**
